language: node_js
node_js: --lts
before_script:
  - git config user.name "Moren YANG"
  - git config user.email "morenyang88@gmail.com"
script:
  - yarn build
after_success:
  - mv build dist
  - git add dist
  - git commit -m "deploy on gh-pages `date`"
  - git subtree push -f --prefix=dist "https://${GITHUB_ACCESS_TOKEN}@github.com/morenyang/neb-paste.git" gh-pages
branches:
  only:
    - master
