language: node_js
node_js: --lts
before_script:
  - git config user.name "Moren YANG"
  - git config user.email "morenyang88@gmail.com"
script:
  - yarn build
after_success:
  - cd build
  - git init
  - git add .
  - git commit -m "deploy on gh-pages `date`"
  - git push --force --quiet "https://${GITHUB_ACCESS_TOKEN}@github.com/morenyang/neb-paste.git" master:gh-pages
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - output
